"""Initial schema

Revision ID: 3b14cead0494
Revises: 
Create Date: 2026-02-27 21:41:16.405586

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3b14cead0494'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('police', 'medical')", name='check_org_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_organizations_type', 'organizations', ['type'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cognito_sub', sa.String(length=255), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('supervisor_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('system_admin', 'dispatcher', 'police_worker', 'police_chief', 'triage_nurse', 'er_doctor', 'er_paramedic', 'er_attending')", name='check_user_role'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supervisor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cognito_sub'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_users_cognito_sub', 'users', ['cognito_sub'], unique=False)
    op.create_index('idx_users_org_id', 'users', ['org_id'], unique=False)
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_index('idx_users_supervisor_id', 'users', ['supervisor_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('schema_type', sa.String(length=50), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("schema_type IN ('incident', 'medical_chart')", name='check_schema_type'),
    sa.CheckConstraint("state IN ('draft', 'in_progress', 'under_review', 'locked')", name='check_report_state'),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reports_assigned_to', 'reports', ['assigned_to'], unique=False)
    op.create_index('idx_reports_created_at', 'reports', ['created_at'], unique=False)
    op.create_index('idx_reports_data_gin', 'reports', ['data'], unique=False, postgresql_using='gin')
    op.create_index('idx_reports_org_id', 'reports', ['org_id'], unique=False)
    op.create_index('idx_reports_state', 'reports', ['state'], unique=False)
    op.create_table('report_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('modified_by', sa.UUID(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_report_history_created_at', 'report_history', ['created_at'], unique=False)
    op.create_index('idx_report_history_report_id', 'report_history', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_report_history_report_id', table_name='report_history')
    op.drop_index('idx_report_history_created_at', table_name='report_history')
    op.drop_table('report_history')
    op.drop_index('idx_reports_state', table_name='reports')
    op.drop_index('idx_reports_org_id', table_name='reports')
    op.drop_index('idx_reports_data_gin', table_name='reports', postgresql_using='gin')
    op.drop_index('idx_reports_created_at', table_name='reports')
    op.drop_index('idx_reports_assigned_to', table_name='reports')
    op.drop_table('reports')
    op.drop_index('idx_users_supervisor_id', table_name='users')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_index('idx_users_org_id', table_name='users')
    op.drop_index('idx_users_cognito_sub', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_organizations_type', table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
